Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2021-09, with the labels that each got.

#43 add bastion ami to af-south-1 region
  pkg/cloud/services/ec2/ami.go
Labels: size/XS

#44 eks: support ng role additional policies
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  exp/controllers/awsmanagedmachinepool_controller.go
  main.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/eks/roles.go
  pkg/eks/identity_provider/plan_test.go
Labels: size/L

#45 update type for mmp role additional policies
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  pkg/cloud/services/eks/roles.go
Labels: size/S
