Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2021-05, with the labels that each got.

#11 add ssm policy to eks nodegroup
  pkg/cloud/services/eks/roles.go
Labels: size/XS

#10 Fargate identity
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  go.sum
  hack/tools/go.sum
  pkg/cloud/scope/fargate.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/userdata/utils.go
Labels: size/L

#12 Fargate reconcile tags
  pkg/cloud/services/eks/fargate.go
  pkg/cloud/services/eks/tags.go
Labels: size/S

#13 add build image script
  capa-build.sh
Labels: size/S

#14 Attach oidc provider
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/conditions_consts.go
  controlplane/eks/api/v1alpha3/types.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  go.mod
  go.sum
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/identity_provider.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
  pkg/eks/identity_provider/plan.go
  pkg/eks/identity_provider/plan_test.go
  pkg/eks/identity_provider/procedures.go
  pkg/eks/identity_provider/types.go
  pkg/eks/identity_provider/types_test.go
Labels: size/XXL

#15 Force deletion
  exp/controllers/awsmanagedmachinepool_controller.go
Labels: size/S
