Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2022-12, with the labels that each got.

#514 remove hardcoded partitions
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
Labels: size/XS

#519 PCP-618: capa fix hardcoded role arn for aws iam authenticator
  cmd/clusterawsadm/api/bootstrap/v1beta1/defaults.go
  cmd/clusterawsadm/cloudformation/bootstrap/fargate.go
  cmd/clusterawsadm/cloudformation/bootstrap/managed_nodegroup.go
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/eks/roles.go
  pkg/cloud/services/iamauth/reconcile.go
  pkg/cloud/services/s3/s3.go
Labels: size/L

#524 Update arn for AmazonEKSClusterPolicy
  pkg/cloud/services/eks/roles.go
Labels: size/S

#523 PCP-230: Fix AWS Cluster Tags Deletion & Re-addition issue
  pkg/cloud/services/network/subnets.go
Labels: size/M
