Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2022-09, with the labels that each got.

#412 BET-6063: deletion fails for aws cluster with vpc limit exceeded
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/network/vpc.go
Labels: size/XS

#435 Bump CAPI to v1.2.0 and e2e test Kubernetes versions to v1.24.0
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: size/XL

#433 remove default eni env config
  docs/book/src/topics/eks/pod-networking.md
  pkg/cloud/services/awsnode/cni.go
  pkg/cloud/services/awsnode/cni_test.go
Labels: size/L

#432 deleting additional vpc cni resources when disabled
  go.mod
  go.sum
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/awsnode/cni.go
Labels: size/M

#431 fix OIDC reattach
  pkg/cloud/converters/eks.go
  pkg/cloud/services/eks/identity_provider.go
  pkg/eks/identityprovider/plan.go
  pkg/eks/identityprovider/plan_test.go
  pkg/eks/identityprovider/procedures.go
  pkg/eks/identityprovider/types.go
  pkg/eks/identityprovider/types_test.go
Labels: size/L

#446 remove second enableGates Call
  main.go
Labels: size/XS

#448 update idp reconciler to get out sooner if nothing to do
  pkg/cloud/services/eks/identity_provider.go
Labels: size/M

#449 add gitattributes file
  .gitattributes
Labels: size/XS

#454 fixing main from merge conflicts
  main.go
Labels: size/M
