Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2023-09, with the labels that each got.

#849 Ingress rule changes 3.4
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/awscluster_types.go
  api/v1beta1/awscluster_webhook.go
  api/v1beta1/network_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/network.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  spectro/generated/core-global.yaml
  spectro/run.sh
Labels: size/XXL

#850 IngressRules changes with NAT updates
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/awscluster_types.go
  api/v1beta1/awscluster_webhook.go
  api/v1beta1/network_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/network.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  spectro/generated/core-global.yaml
  spectro/run.sh
Labels: size/XXL

#851 IngressRules changes with NAT updates
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/awscluster_types.go
  api/v1beta1/awscluster_webhook.go
  api/v1beta1/network_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/network.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  spectro/generated/core-global.yaml
  spectro/run.sh
Labels: size/XXL

#852 Try Arm Build
  Makefile
Labels: size/XS

#854 Update caBundle with actual value for tests
  spectro/generated/core-global.yaml
  spectro/global/kustomization.yaml
  spectro/global/patch_cabundle.yaml
Labels: size/L

#855 fixed caBundle yaml decoding issue
  spectro/generated/core-global.yaml
  spectro/global/patch_cabundle.yaml
Labels: size/M

#853 Support CIDR Blocks for NodePortRules
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/network_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/securitygroup/securitygroups.go
  spectro/generated/core-global.yaml
Labels: size/L

#857 PCP-1845: Update builder image and go version
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#856 PCP-1845: Update builder image and go version
  Dockerfile
  go.mod
  go.sum
Labels: size/S

#858 Sync with 4.0
  Dockerfile
  Makefile
Labels: size/S
