Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2023-06, with the labels that each got.

#730 Spectro CICD
  .github/workflows/spectro-release.yaml
  Dockerfile
  Makefile
Labels: size/M

#743 adding patches to join config
  pkg/cloud/services/iam/oidc.go
Labels: size/S

#744 adding patches to join config
  pkg/cloud/services/iam/oidc.go
Labels: size/S

#757 Fix GH workflow
  .github/workflows/spectro-release.yaml
  Dockerfile
  Makefile
Labels: size/M

#760 Fips changes for Static Linking
  .github/workflows/spectro-release.yaml
  Dockerfile
Labels: size/S

#761 Fips changes for Static Linking
  .github/workflows/spectro-release.yaml
  Dockerfile
Labels: size/S

#766 change to s3.<region>.amazonaws.com dns
  pkg/cloud/services/iam/iam.go
Labels: size/XS
