Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2023-08, with the labels that each got.

#796 PEM-2613: Fix cipher suit issue
  go.mod
  go.sum
  main.go
Labels: size/L

#799 PCP-1561: OIDC identity providers created by Spectrocloud are not get…
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/oidc.go
Labels: size/S

#804 [rel] PEM-2613: Update cipher suit
  main.go
Labels: size/XS

#808 PCP-1654: CAPA Cipher suit add boringcrypto flag for Max version
  main.go
  util/flags/tls_boring.go
  util/flags/tls_non_boring.go
Labels: size/M

#812 Pcp 1428 4.0
  pkg/cloud/scope/session.go
  pkg/utils/resolver_endpoint.go
  pkg/utils/resolver_endpoint_test.go
Labels: size/L

#822 PCP-1190: AWS with irsa configuration Cluster stuck in deletion
  pkg/cloud/services/s3/s3.go
  pkg/utils/resolver_endpoint.go
Labels: size/L

#825 PCP-1428: AWS CAPA changes to consume AWS FIPS endpoints
  pkg/cloud/scope/session.go
  pkg/utils/resolver_endpoint.go
  pkg/utils/resolver_endpoint_test.go
Labels: size/L
