Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2024-12, with the labels that each got.

#915 PCP-3571 EKS Security Group tag updation from AWSManagedControlPlane
  go.mod
  go.sum
  pkg/cloud/services/eks/securitygroup.go
  pkg/cloud/services/eks/securitygroup_test.go
Labels: size/L

#924 PCP-3764: attached tags to the volume when launched
  pkg/cloud/services/ec2/instances.go
Labels: size/XS

#879 log set of issues when node group in degraded state
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/nodegroup_test.go
Labels: size/M

#926 log set of issues when node group in degraded state
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/nodegroup_test.go
Labels: size/M
