Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2025-04, with the labels that each got.

#956 PCP-3797: Added nil pointer check before dereferencing Nodegroup version
  pkg/cloud/services/eks/nodegroup.go
Labels: size/XS

#960 PCP-3797: [Backport] Fix from #956 to spectro-release-4.6
  pkg/cloud/services/eks/nodegroup.go
Labels: size/XS

#959 controller and webhook separation in main.go
  main.go
Labels: size/L

#906 PCP-4375: 🚀 SUS-564: Support AL 2023
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  docs/book/src/crd/index.md
  exp/api/v1beta1/awsmanagedmachinepool_types.go
Labels: size/S
