Repository spectrocloud/cluster-api-provider-aws, pull requests merged in 2025-05, with the labels that each got.

#964 Fix duplicate tag issue: InvalidParameterValue: The same resource type may not be specified more than once in tag specifications
  pkg/cloud/services/ec2/instances.go
Labels: size/XS

#965 PCP-4496: feat: add AL2023 nvidia neuron to AWSMMP v1beta2
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
Labels: size/XS

#966 feat: update AWSMMP to include AL2023_x86_64_NEURON/NVIDIA
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1beta2/awsmanagedmachinepool_types.go
Labels: size/XS

#967 PCP-4523 : EKS: Validate IRSA support
  pkg/cloud/services/eks/oidc.go
  pkg/utils/resolver_endpoint.go
Labels: size/M

#969 webhook seperation
  main.go
Labels: size/L
